<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>analyticsedge - The Analytics Edge: Assignment 1 - An Introduction to Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Assignments/Assignment2.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">The Analytics Edge: Assignment 1 - An Introduction to Analytics</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">analyticsedge</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">The Analytics Edge: Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Assignments/Assignment1.html" class="sidebar-item-text sidebar-link active">The Analytics Edge: Assignment 1 - An Introduction to Analytics</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Assignments/Assignment2.html" class="sidebar-item-text sidebar-link">The Analytics Edge: Assignment 2 - Linear Regression</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#an-analytical-detective" id="toc-an-analytical-detective" class="nav-link active" data-scroll-target="#an-analytical-detective">An Analytical Detective</a></li>
  <li><a href="#stock-dynamics" id="toc-stock-dynamics" class="nav-link" data-scroll-target="#stock-dynamics">Stock Dynamics</a></li>
  <li><a href="#demographics-and-employment-in-the-united-states" id="toc-demographics-and-employment-in-the-united-states" class="nav-link" data-scroll-target="#demographics-and-employment-in-the-united-states">Demographics and Employment in the United States</a></li>
  <li><a href="#internet-privacy-poll-optional" id="toc-internet-privacy-poll-optional" class="nav-link" data-scroll-target="#internet-privacy-poll-optional">Internet Privacy Poll (OPTIONAL)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">The Analytics Edge: Assignment 1 - An Introduction to Analytics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The following link will lead you to the assignment on the edX website: <a href="https://learning.edx.org/course/course-v1:MITx+15.071x+2T2020/block-v1:MITx+15.071x+2T2020+type@sequential+block@a5915d0492804dada5feb1926ba5be7a">https://learning.edx.org/course/course-v1:MITx+15.071x+2T2020/block-v1:MITx+15.071x+2T2020+type@sequential+block@a5915d0492804dada5feb1926ba5be7a</a></p>
<section id="an-analytical-detective" class="level2">
<h2 class="anchored" data-anchor-id="an-analytical-detective">An Analytical Detective</h2>
<p>There are two main types of crimes: violent crimes, and property crimes. In this problem, we’ll focus on one specific type of property crime, called “motor vehicle theft” (sometimes referred to as grand theft auto). This is the act of stealing, or attempting to steal, a car. In this problem, we’ll use some basic data analysis in R to understand the motor vehicle thefts in Chicago.</p>
<p>Please download the file <a href="https://courses.edx.org/assets/courseware/v1/96f9b8f751467da3a4b8a5be33e32905/asset-v1:MITx+15.071x+2T2020+type@asset+block/mvtWeek1.csv">mvtWeek1.csv</a> for this problem (do not open this file in any spreadsheet software before completing this problem because it might change the format of the Date field).</p>
<p><strong><em>Start:</em></strong><br>
Read the dataset mvtWeek1.csv into R, using the read.csv function, and call the data frame “mvt”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mvt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/mvtWeek1.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>1.1: How many rows of data (observations) are in this dataset?</strong><br>
Answer: 191641</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mvt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 191641</code></pre>
</div>
</div>
<p><strong>1.2: How many variables are in this dataset?</strong><br>
Answer: 11</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(mvt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
</div>
<p><strong>1.3: Using the “max” function, what is the maximum value of the variable “ID”?</strong><br>
Answer: 9181151</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(mvt<span class="sc">$</span>ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9181151</code></pre>
</div>
</div>
<p><strong>1.4: What is the minimum value of the variable “Beat”?</strong><br>
Answer: 111</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(mvt<span class="sc">$</span>Beat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 111</code></pre>
</div>
</div>
<p><strong>1.5: How many observations have value TRUE in the Arrest variable (this is the number of crimes for which an arrest was made)?</strong><br>
Answer: 15536</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mvt<span class="sc">$</span>Arrest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15536</code></pre>
</div>
</div>
<p><strong>1.6: How many observations have a LocationDescription value of ALLEY?</strong><br>
Answer: 2308</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"ALLEY"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2308</code></pre>
</div>
</div>
<p><strong>2.1: In what format are the entries in the variable Date?</strong><br>
Answer: Month/Day/Year Hour:Minute</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mvt<span class="sc">$</span>Date[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "12/31/12 23:15"</code></pre>
</div>
</div>
<p><strong>2.2: What is the month and year of the median date in our dataset? Enter your answer as “Month Year”, without the quotes.</strong><br>
Answer: May 2006</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>DateConvert <span class="ot">=</span> <span class="fu">as.Date</span>(<span class="fu">strptime</span>(mvt<span class="sc">$</span>Date, <span class="st">"%m/%d/%y %H:%M"</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(DateConvert)</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(DateConvert)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2006-05-21"</code></pre>
</div>
</div>
<p><strong>2.3: In which month did the fewest motor vehicle thefts occur?</strong><br>
Answer: February</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mvt<span class="sc">$</span>Month <span class="ot">=</span> <span class="fu">months</span>(DateConvert)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mvt<span class="sc">$</span>Weekday <span class="ot">=</span> <span class="fu">weekdays</span>(DateConvert)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>mvt<span class="sc">$</span>Date <span class="ot">=</span> DateConvert</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mvt<span class="sc">$</span>Month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    April    August  December  February   January      July      June     March 
    15280     16572     16426     13511     16047     16801     16002     15758 
      May  November   October September 
    16035     16063     17086     16060 </code></pre>
</div>
</div>
<p><strong>2.4: On which weekday did the most motor vehicle thefts occur?</strong><br>
Answer: Friday</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mvt<span class="sc">$</span>Weekday)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Friday    Monday  Saturday    Sunday  Thursday   Tuesday Wednesday 
    29284     27397     27118     26316     27319     26791     27416 </code></pre>
</div>
</div>
<p><strong>2.5: Which month has the largest number of motor vehicle thefts for which an arrest was made?</strong><br>
Answer: January</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mvt<span class="sc">$</span>Month, mvt<span class="sc">$</span>Arrest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            FALSE  TRUE
  April     14028  1252
  August    15243  1329
  December  15029  1397
  February  12273  1238
  January   14612  1435
  July      15477  1324
  June      14772  1230
  March     14460  1298
  May       14848  1187
  November  14807  1256
  October   15744  1342
  September 14812  1248</code></pre>
</div>
</div>
<p><strong>3.1.1: In general, does it look like crime increases or decreases from 2002 - 2012?</strong><br>
Answer: Decreases</p>
<p><strong>3.1.2: In general, does it look like crime increases or decreases from 2005 - 2008?</strong><br>
Answer: Decreases</p>
<p><strong>3.1.3: In general, does it look like crime increases or decreases from 2009 - 2011?</strong><br>
Answer: Increases</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mvt<span class="sc">$</span>Date, <span class="at">breaks=</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>3.2: Does it look like there were more crimes for which arrests were made in the first half of the time period or the second half of the time period?</strong><br>
Answer: First half</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Date <span class="sc">~</span> Arrest, <span class="at">data =</span> mvt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>3.3: For what proportion of motor vehicle thefts in 2001 was an arrest made?</strong><br>
Answer: 0.1041173</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(mvt<span class="sc">$</span>Arrest, mvt<span class="sc">$</span>Year, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2001       2002       2003       2004       2005       2006       2007 
0.10411728 0.11278195 0.10794261 0.10040327 0.09269595 0.08087961 0.08487395 
      2008       2009       2010       2011       2012 
0.07061267 0.06903920 0.04523456 0.03996930 0.03902924 </code></pre>
</div>
</div>
<p><strong>3.4: For what proportion of motor vehicle thefts in 2007 was an arrest made?</strong><br>
Answer: 0.08487395</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(mvt<span class="sc">$</span>Arrest, mvt<span class="sc">$</span>Year, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2001       2002       2003       2004       2005       2006       2007 
0.10411728 0.11278195 0.10794261 0.10040327 0.09269595 0.08087961 0.08487395 
      2008       2009       2010       2011       2012 
0.07061267 0.06903920 0.04523456 0.03996930 0.03902924 </code></pre>
</div>
</div>
<p><strong>3.5: For what proportion of motor vehicle thefts in 2012 was an arrest made?</strong><br>
Answer: 0.03902924</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(mvt<span class="sc">$</span>Arrest, mvt<span class="sc">$</span>Year, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2001       2002       2003       2004       2005       2006       2007 
0.10411728 0.11278195 0.10794261 0.10040327 0.09269595 0.08087961 0.08487395 
      2008       2009       2010       2011       2012 
0.07061267 0.06903920 0.04523456 0.03996930 0.03902924 </code></pre>
</div>
</div>
<p><strong>4.1: Which locations are the top five locations for motor vehicle thefts, excluding the “Other” category?</strong><br>
Answer: STREET, PARKING LOT/GARAGE(NON.RESID.), ALLEY, GAS STATION, DRIVEWAY - RESIDENTIAL</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(mvt<span class="sc">$</span>LocationDescription), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                         STREET 
                                         156564 
                 PARKING LOT/GARAGE(NON.RESID.) 
                                          14852 
                                          OTHER 
                                           4573 
                                          ALLEY 
                                           2308 
                                    GAS STATION 
                                           2111 
                         DRIVEWAY - RESIDENTIAL 
                                           1675 
                  RESIDENTIAL YARD (FRONT/BACK) 
                                           1536 
                                      RESIDENCE 
                                           1302 
                               RESIDENCE-GARAGE 
                                           1176 
                                VACANT LOT/LAND 
                                            985 
                         VEHICLE NON-COMMERCIAL 
                                            817 
                                       SIDEWALK 
                                            462 
                        CHA PARKING LOT/GROUNDS 
                                            405 
                               AIRPORT/AIRCRAFT 
                                            363 
                POLICE FACILITY/VEH PARKING LOT 
                                            266 
                                  PARK PROPERTY 
                                            255 
                        SCHOOL, PUBLIC, GROUNDS 
                                            206 
                                      APARTMENT 
                                            184 
                           SPORTS ARENA/STADIUM 
                                            166 
                    CTA GARAGE / OTHER PROPERTY 
                                            148 
                   COMMERCIAL / BUSINESS OFFICE 
                                            126 
                                    HOTEL/MOTEL 
                                            124 
                       SCHOOL, PUBLIC, BUILDING 
                                            114 
                      HOSPITAL BUILDING/GROUNDS 
                                            101 
                             GROCERY FOOD STORE 
                                             80 
              CHURCH/SYNAGOGUE/PLACE OF WORSHIP 
                                             56 
                                     RESTAURANT 
                                             49 
                   GOVERNMENT BUILDING/PROPERTY 
                                             48 
                     COLLEGE/UNIVERSITY GROUNDS 
                                             47 
                                       CAR WASH 
                                             44 
                              CONSTRUCTION SITE 
                                             35 
                             SMALL RETAIL STORE 
                                             33 
              OTHER RAILROAD PROP / TRAIN DEPOT 
                                             28 
             AIRPORT EXTERIOR - NON-SECURE AREA 
                                             24 
                       SCHOOL, PRIVATE, GROUNDS 
                                             23 
                             VEHICLE-COMMERCIAL 
                                             23 
                               DEPARTMENT STORE 
                                             22 
                             HIGHWAY/EXPRESSWAY 
                                             22 
                   NURSING HOME/RETIREMENT HOME 
                                             21 
                                        TAXICAB 
                                             21 
                            MOVIE HOUSE/THEATER 
                                             18 
                        RESIDENCE PORCH/HALLWAY 
                                             18 
                                  BAR OR TAVERN 
                                             17 
                                      WAREHOUSE 
                                             17 
                 FACTORY/MANUFACTURING BUILDING 
                                             16 
                      SCHOOL, PRIVATE, BUILDING 
                                             14 
                            TAVERN/LIQUOR STORE 
                                             14 
                            AIRPORT PARKING LOT 
                                             11 
                  AIRPORT VENDING ESTABLISHMENT 
                                             10 
                                  ATHLETIC CLUB 
                                              9 
                                     DRUG STORE 
                                              8 
                OTHER COMMERCIAL TRANSPORTATION 
                                              8 
                                           BANK 
                                              7 
                              CONVENIENCE STORE 
                                              7 
                                FOREST PRESERVE 
                                              6 
 AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA 
                                              5 
                                  CHA APARTMENT 
                                              5 
                                DAY CARE CENTER 
                                              5 
                                   FIRE STATION 
                                              5 
                             ABANDONED BUILDING 
                                              4 
AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA 
                                              4 
                                     BARBERSHOP 
                                              4 
                 LAKEFRONT/WATERFRONT/RIVERBANK 
                                              4 
                                        LIBRARY 
                                              4 
                               SAVINGS AND LOAN 
                                              4 
                                  BOWLING ALLEY 
                                              3 
                                 CLEANING STORE 
                                              3 
                          MEDICAL/DENTAL OFFICE 
                                              3 
                                         BRIDGE 
                                              2 
              COLLEGE/UNIVERSITY RESIDENCE HALL 
                                              2 
                              CURRENCY EXCHANGE 
                                              2 
    AIRPORT BUILDING NON-TERMINAL - SECURE AREA 
                                              1 
                 AIRPORT EXTERIOR - SECURE AREA 
                                              1 
                                ANIMAL HOSPITAL 
                                              1 
                                APPLIANCE STORE 
                                              1 
                                      CTA TRAIN 
                                              1 
                        JAIL / LOCK-UP FACILITY 
                                              1 
                                      NEWSSTAND 
                                              1 </code></pre>
</div>
</div>
<p><strong>Create a subset of your data, only taking observations for which the theft happened in one of these five locations, and call this new data set “Top5”:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Top5 <span class="ot">&lt;-</span> <span class="fu">subset</span>(mvt, mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"STREET"</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>       <span class="sc">|</span> mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"PARKING LOT/GARAGE(NON.RESID.)"</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>       <span class="sc">|</span> mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"ALLEY"</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>       <span class="sc">|</span> mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"GAS STATION"</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>       <span class="sc">|</span> mvt<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"DRIVEWAY - RESIDENTIAL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>4.2: How many observations are in Top5?</strong><br>
Answer: 177510</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Top5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 177510</code></pre>
</div>
</div>
<p><strong>4.3: One of the locations has a much higher arrest rate than the other locations. Which is it?</strong><br>
Answer: Gas Station (Check percentages)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>Top5<span class="sc">$</span>LocationDescription <span class="ot">=</span> <span class="fu">factor</span>(Top5<span class="sc">$</span>LocationDescription)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Top5<span class="sc">$</span>LocationDescription, Top5<span class="sc">$</span>Arrest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                
                                  FALSE   TRUE
  ALLEY                            2059    249
  DRIVEWAY - RESIDENTIAL           1543    132
  GAS STATION                      1672    439
  PARKING LOT/GARAGE(NON.RESID.)  13249   1603
  STREET                         144969  11595</code></pre>
</div>
</div>
<p><strong>4.4: On which day of the week do the most motor vehicle thefts at gas stations happen?</strong><br>
Answer: Saturday</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Top5<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"GAS STATION"</span>, Top5<span class="sc">$</span>Weekday)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Friday Monday Saturday Sunday Thursday Tuesday Wednesday
  FALSE  26746  25008    24917  24220    24956   24527     25025
  TRUE     332    280      338    336      282     270       273</code></pre>
</div>
</div>
<p><strong>4.5: On which day of the week do the fewest motor vehicle thefts in residential driveways happen?</strong><br>
Answer: Saturday</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Top5<span class="sc">$</span>LocationDescription <span class="sc">==</span> <span class="st">"DRIVEWAY - RESIDENTIAL"</span>, Top5<span class="sc">$</span>Weekday)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Friday Monday Saturday Sunday Thursday Tuesday Wednesday
  FALSE  26821  25033    25053  24335    24975   24554     25064
  TRUE     257    255      202    221      263     243       234</code></pre>
</div>
</div>
</section>
<section id="stock-dynamics" class="level2">
<h2 class="anchored" data-anchor-id="stock-dynamics">Stock Dynamics</h2>
<p>A stock market is where buyers and sellers trade shares of a company, and is one of the most popular ways for individuals and companies to invest money. The size of the world stock market is now estimated to be in the trillions. The largest stock market in the world is the New York Stock Exchange (NYSE), located in New York City. About 2,800 companies are listed on the NYSE. In this problem, we’ll look at the monthly stock prices of five of these companies: IBM, General Electric (GE), Procter and Gamble, Coca Cola, and Boeing. The data used in this problem comes from Infochimps.</p>
<p>Please download the following files: <a href="https://courses.edx.org/assets/courseware/v1/4fc08d10f171aacf2ef61c6b4b5bb4d8/asset-v1:MITx+15.071x+2T2020+type@asset+block/IBMStock.csv">IBMStock.csv</a>, <a href="https://courses.edx.org/assets/courseware/v1/448b8be4693d913c2b5153be0c0e25d6/asset-v1:MITx+15.071x+2T2020+type@asset+block/GEStock.csv">GEStock.csv</a>, <a href="https://courses.edx.org/assets/courseware/v1/bb6ed54230b5b2e29fb66819ed535da0/asset-v1:MITx+15.071x+2T2020+type@asset+block/ProcterGambleStock.csv">ProcterGambleStock.csv</a>, <a href="https://courses.edx.org/assets/courseware/v1/4c30fd7f4f55e537989ca13a6db36289/asset-v1:MITx+15.071x+2T2020+type@asset+block/CocaColaStock.csv">CocaColaStock.csv</a>, <a href="https://courses.edx.org/assets/courseware/v1/2e8c9fb294db48e5a999c747b317722d/asset-v1:MITx+15.071x+2T2020+type@asset+block/BoeingStock.csv">BoeingStock.csv</a> (do not open these files in any spreadsheet software before completing this problem because it might change the format of the Date field).</p>
<p><strong><em>Start:</em></strong><br>
Read the datasets into R, using the read.csv function, and call the data frames “IBM”, “GE”, “ProcterGamble”, “CocaCola”, and “Boeing”, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>IBM <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/IBMStock.csv"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>GE <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/GEStock.csv"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>ProcterGamble <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/ProcterGambleStock.csv"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>CocaCola <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/CocaColaStock.csv"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>Boeing <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/BoeingStock.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before working with these data sets, we need to convert the dates into a format that R can understand. Take a look at the structure of one of the datasets using the str function. Right now, the date variable is stored as a factor. We can convert this to a “Date” object in R by using the following five commands (one for each data set):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>IBM<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">as.Date</span>(IBM<span class="sc">$</span>Date, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>GE<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">as.Date</span>(GE<span class="sc">$</span>Date, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>CocaCola<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">as.Date</span>(CocaCola<span class="sc">$</span>Date, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>ProcterGamble<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">as.Date</span>(ProcterGamble<span class="sc">$</span>Date, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>Boeing<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">as.Date</span>(Boeing<span class="sc">$</span>Date, <span class="st">"%m/%d/%y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>1.1: Our five datasets all have the same number of observations. How many observations are there in each data set?</strong><br>
Answer: 480</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(IBM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 480</code></pre>
</div>
</div>
<p><strong>1.2: What is the earliest year in our datasets?</strong><br>
Answer: 1970</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(IBM<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1970-01-01"</code></pre>
</div>
</div>
<p><strong>1.3: What is the latest year in our datasets?</strong><br>
Answer: 2009</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(IBM<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2009-12-01"</code></pre>
</div>
</div>
<p><strong>1.4: What is the mean stock price of IBM over this time period?</strong><br>
Answer: 144.375</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(IBM<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144.375</code></pre>
</div>
</div>
<p><strong>1.5: What is the minimum stock price of General Electric (GE) over this time period?</strong><br>
Answer: 9.293636</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(GE<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.293636</code></pre>
</div>
</div>
<p><strong>1.6: What is the maximum stock price of Coca-Cola over this time period?</strong><br>
Answer: 146.5843</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(CocaCola<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 146.5843</code></pre>
</div>
</div>
<p><strong>1.7: What is the median stock price of Boeing over this time period?</strong><br>
Answer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(Boeing<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.8834</code></pre>
</div>
</div>
<p><strong>1.8: What is the standard deviation of the stock price of Procter &amp; Gamble over this time period?</strong><br>
Answer: 18.19414</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(ProcterGamble<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.19414</code></pre>
</div>
</div>
<p>Side note: According to the assignment, questions 1.2 - 1.7 should’ve been solved using the summary function. However, I used commands that would give more accurate answer. Along with the commands I used, I also wrote how the assignment could be solved using the summary function.</p>
<p><strong>2.1.1: Around what year did Coca-Cola has its highest stock price in this time period?</strong><br>
Answer: 1973</p>
<p><strong>2.1.2: Around what year did Coca-Cola has its lowest stock price in this time period?</strong><br>
Answer: 1980</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date, CocaCola<span class="sc">$</span>StockPrice, <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>2.2: In March of 2000, the technology bubble burst, and a stock market crash occurred. According to this plot, which company’s stock dropped more?</strong><br>
Answer: Procter and Gamble</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date, CocaCola<span class="sc">$</span>StockPrice, <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ProcterGamble<span class="sc">$</span>Date, ProcterGamble<span class="sc">$</span>StockPrice, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"2000-03-01"</span>)), <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>2.3.1: Around 1983, the stock for one of these companies (Coca-Cola or Procter and Gamble) was going up, while the other was going down. Which one was going up?</strong><br>
Answer: CocaCola</p>
<p><strong>2.3.1: In the time period shown in the plot, which stock generally has lower values?</strong><br>
Answer: CocaCola</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date, CocaCola<span class="sc">$</span>StockPrice, <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ProcterGamble<span class="sc">$</span>Date, ProcterGamble<span class="sc">$</span>StockPrice, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"1983-01-01"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Plot to answer the following questions:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], CocaCola<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">type=</span><span class="st">"l"</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">210</span>))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ProcterGamble<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], ProcterGamble<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(IBM<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], IBM<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(GE<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], GE<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"purple"</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Boeing<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], Boeing<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"orange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>3.1: Which stock fell the most right after the technology bubble burst in March 2000?</strong><br>
Answer: General Electric (GE)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], CocaCola<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">type=</span><span class="st">"l"</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">210</span>))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ProcterGamble<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], ProcterGamble<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(IBM<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], IBM<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(GE<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], GE<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"purple"</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Boeing<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], Boeing<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"orange"</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"2000-03-01"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>3.2: Which stock reaches the highest value in the time period 1995-2005?</strong><br>
Answer: IBM</p>
<p><strong>3.3: Comparing September 1997 to November 1997, which companies saw a decreasing trend in their stock price?</strong><br>
Answer: Procer and Gamble, Boeing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(CocaCola<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], CocaCola<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">type=</span><span class="st">"l"</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">210</span>))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ProcterGamble<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], ProcterGamble<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(IBM<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], IBM<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(GE<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], GE<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"purple"</span>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Boeing<span class="sc">$</span>Date[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], Boeing<span class="sc">$</span>StockPrice[<span class="dv">301</span><span class="sc">:</span><span class="dv">432</span>], <span class="at">col =</span> <span class="st">"orange"</span>)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"1997-09-1"</span>)))</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"1997-11-1"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>3.4: In the last two years of this time period (2004 and 2005) which stock seems to be performing the best, in terms of increasing stock price?</strong><br>
Answer: Boeing</p>
<p><strong>4.1: In which months has IBM historically had a higher stock price (on average)?</strong><br>
Answer: January, February, March, April, May</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(IBM<span class="sc">$</span>StockPrice, <span class="fu">months</span>(IBM<span class="sc">$</span>Date), mean) <span class="sc">&gt;</span> <span class="fu">mean</span>(IBM<span class="sc">$</span>StockPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    April    August  December  February   January      July      June     March 
     TRUE     FALSE     FALSE      TRUE      TRUE     FALSE     FALSE      TRUE 
      May  November   October September 
     TRUE     FALSE     FALSE     FALSE </code></pre>
</div>
</div>
<p><strong>4.2: General Electric and Coca-Cola both have their highest average stock price in the same month. Which month is this?</strong><br>
Answer: April</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(GE<span class="sc">$</span>StockPrice, <span class="fu">months</span>(GE<span class="sc">$</span>Date), mean) <span class="sc">==</span> <span class="fu">max</span>(<span class="fu">tapply</span>(GE<span class="sc">$</span>StockPrice, <span class="fu">months</span>(GE<span class="sc">$</span>Date), mean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    April    August  December  February   January      July      June     March 
     TRUE     FALSE     FALSE     FALSE     FALSE     FALSE     FALSE     FALSE 
      May  November   October September 
    FALSE     FALSE     FALSE     FALSE </code></pre>
</div>
</div>
<p><strong>4.3: For the months of December and January, every company’s average stock is higher in one month and lower in the other. In which month are the stock prices lower?</strong><br>
Answer: December</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(GE<span class="sc">$</span>StockPrice, <span class="fu">months</span>(GE<span class="sc">$</span>Date), mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    April    August  December  February   January      July      June     March 
 64.48009  56.50315  59.10217  62.52080  62.04511  56.73349  56.46844  63.15055 
      May  November   October September 
 60.87135  57.28879  56.23897  56.23913 </code></pre>
</div>
</div>
</section>
<section id="demographics-and-employment-in-the-united-states" class="level2">
<h2 class="anchored" data-anchor-id="demographics-and-employment-in-the-united-states">Demographics and Employment in the United States</h2>
<p>In the wake of the Great Recession of 2009, there has been a good deal of focus on employment statistics, one of the most important metrics policymakers use to gauge the overall strength of the economy. In the United States, the government measures unemployment using the Current Population Survey (CPS), which collects demographic and employment information from a wide range of Americans each month. In this exercise, we will employ the topics reviewed in the lectures as well as a few new techniques using the September 2013 version of this rich, nationally representative dataset (available online).</p>
<p>The observations in the dataset represent people surveyed in the September 2013 CPS who actually completed a survey. While the full dataset has 385 variables, in this exercise we will use a more compact version of the dataset.</p>
<p>Please dowload the following file: <a href="https://courses.edx.org/assets/courseware/v1/f041f6c100061fc06bc3b6320e6512fa/asset-v1:MITx+15.071x+2T2020+type@asset+block/CPSData.csv">CPSData.csv</a></p>
<p><strong><em>Start:</em></strong><br>
Load the dataset from CPSData.csv into a data frame called CPS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>CPS <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/CPSData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>1.1: How many interviewees are in the dataset?</strong><br>
Answer: 131302</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(CPS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131302</code></pre>
</div>
</div>
<p><strong>1.2: Among the interviewees with a value reported for the Industry variable, what is the most common industry of employment?</strong><br>
Answer: Educational and health services</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(CPS<span class="sc">$</span>Industry), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Educational and health services 
                          15017 </code></pre>
</div>
</div>
<p><strong>1.3.1: Which state has the fewest interviewees?</strong><br>
Answer: New Mexico</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">sort</span>(<span class="fu">table</span>(CPS<span class="sc">$</span>State), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
New Mexico 
      1102 </code></pre>
</div>
</div>
<p><strong>1.3.2: Which state has the largest number of interviewees?</strong><br>
Answer: California</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(CPS<span class="sc">$</span>State), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
California 
     11570 </code></pre>
</div>
</div>
<p><strong>1.4: What proportion of interviewees are citizens of the United States?</strong><br>
Answer: 0.9421943</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Citizenship)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Citizen, Native Citizen, Naturalized          Non-Citizen 
              116639                 7073                 7590 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">116639</span> <span class="sc">+</span> <span class="dv">7073</span>)<span class="sc">/</span><span class="fu">nrow</span>(CPS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9421943</code></pre>
</div>
</div>
<p><strong>1.5: For which races are there at least 250 interviewees in the CPS dataset of Hispanic ethnicity?</strong><br>
Answer: American Indian, Black, Multiracial, White</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Race, CPS<span class="sc">$</span>Hispanic) <span class="sc">&gt;</span> <span class="dv">250</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  
                      0     1
  American Indian  TRUE  TRUE
  Asian            TRUE FALSE
  Black            TRUE  TRUE
  Multiracial      TRUE  TRUE
  Pacific Islander TRUE FALSE
  White            TRUE  TRUE</code></pre>
</div>
</div>
<p><strong>2.1: Which variables have at least one interviewee with a missing (NA) value?</strong><br>
Answer: MetroAreaCode, Married, Education, EmploymentStatus, Industry</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(CPS)) <span class="sc">&gt;</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MetroAreaCode"    "Married"          "Education"        "EmploymentStatus"
[5] "Industry"        </code></pre>
</div>
</div>
<p><strong>2.2: We will try to determine if there is a pattern in the missing values of the Married variable.</strong><br>
Answer: The Married variable being missing is related to the Age value for the interviewee.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Region, <span class="fu">is.na</span>(CPS<span class="sc">$</span>Married))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            FALSE  TRUE
  Midwest   24609  6075
  Northeast 21432  4507
  South     33535  7967
  West      26388  6789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Sex, <span class="fu">is.na</span>(CPS<span class="sc">$</span>Married))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         FALSE  TRUE
  Female 55264 12217
  Male   50700 13121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Age, <span class="fu">is.na</span>(CPS<span class="sc">$</span>Married))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     FALSE TRUE
  0      0 1283
  1      0 1559
  2      0 1574
  3      0 1693
  4      0 1695
  5      0 1795
  6      0 1721
  7      0 1681
  8      0 1729
  9      0 1748
  10     0 1750
  11     0 1721
  12     0 1797
  13     0 1802
  14     0 1790
  15  1795    0
  16  1751    0
  17  1764    0
  18  1596    0
  19  1517    0
  20  1398    0
  21  1525    0
  22  1536    0
  23  1638    0
  24  1627    0
  25  1604    0
  26  1643    0
  27  1657    0
  28  1736    0
  29  1645    0
  30  1854    0
  31  1762    0
  32  1790    0
  33  1804    0
  34  1653    0
  35  1716    0
  36  1663    0
  37  1531    0
  38  1530    0
  39  1542    0
  40  1571    0
  41  1673    0
  42  1711    0
  43  1819    0
  44  1764    0
  45  1749    0
  46  1665    0
  47  1647    0
  48  1791    0
  49  1989    0
  50  1966    0
  51  1931    0
  52  1935    0
  53  1994    0
  54  1912    0
  55  1895    0
  56  1935    0
  57  1827    0
  58  1874    0
  59  1758    0
  60  1746    0
  61  1735    0
  62  1595    0
  63  1596    0
  64  1519    0
  65  1569    0
  66  1577    0
  67  1227    0
  68  1130    0
  69  1062    0
  70  1195    0
  71  1031    0
  72   941    0
  73   896    0
  74   842    0
  75   763    0
  76   729    0
  77   698    0
  78   659    0
  79   661    0
  80  2664    0
  85  2446    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Citizenship, <span class="fu">is.na</span>(CPS<span class="sc">$</span>Married))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      
                       FALSE  TRUE
  Citizen, Native      91956 24683
  Citizen, Naturalized  6910   163
  Non-Citizen           7098   492</code></pre>
</div>
</div>
<p><strong>2.3.1: How many states had all interviewees living in a non-metropolitan area (aka they have a missing MetroAreaCode value)? For this question, treat the District of Columbia as a state (even though it is not technically a state).</strong><br>
Answer: 2</p>
<p><strong>2.3.2: How many states had all interviewees living in a metropolitan area? Again, treat the District of Columbia as a state.</strong><br>
Answer: 3</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>State, <span class="fu">is.na</span>(CPS<span class="sc">$</span>MetroAreaCode))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      
                       FALSE  TRUE
  Alabama               1020   356
  Alaska                   0  1590
  Arizona               1327   201
  Arkansas               724   697
  California           11333   237
  Colorado              2545   380
  Connecticut           2593   243
  Delaware              1696   518
  District of Columbia  1791     0
  Florida               4947   202
  Georgia               2250   557
  Hawaii                1576   523
  Idaho                  761   757
  Illinois              3473   439
  Indiana               1420   584
  Iowa                  1297  1231
  Kansas                1234   701
  Kentucky               908   933
  Louisiana             1216   234
  Maine                  909  1354
  Maryland              2978   222
  Massachusetts         1858   129
  Michigan              2517   546
  Minnesota             2150   989
  Mississippi            376   854
  Missouri              1440   705
  Montana                199  1015
  Nebraska               816  1133
  Nevada                1609   247
  New Hampshire         1148  1514
  New Jersey            2567     0
  New Mexico             832   270
  New York              5144   451
  North Carolina        1642   977
  North Dakota           432  1213
  Ohio                  2754   924
  Oklahoma              1024   499
  Oregon                1519   424
  Pennsylvania          3245   685
  Rhode Island          2209     0
  South Carolina        1139   519
  South Dakota           595  1405
  Tennessee             1149   635
  Texas                 6060  1017
  Utah                  1455   387
  Vermont                657  1233
  Virginia              2367   586
  Washington            1937   429
  West Virginia          344  1065
  Wisconsin             1882   804
  Wyoming                  0  1624</code></pre>
</div>
</div>
<p><strong>2.4: Which region of the United States has the largest proportion of interviewees living in a non-metropolitan area?</strong><br>
Answer: Midwest</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CPS<span class="sc">$</span>Region, <span class="fu">is.na</span>(CPS<span class="sc">$</span>MetroAreaCode))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            FALSE  TRUE
  Midwest   20010 10674
  Northeast 20330  5609
  South     31631  9871
  West      25093  8084</code></pre>
</div>
</div>
<p><strong>2.5.1: Which state has a proportion of interviewees living in a non-metropolitan area closest to 30%?</strong><br>
Answer: Wisconsin</p>
<p><strong>2.5.2: Which state has the largest proportion of non-metropolitan interviewees, ignoring states where all interviewees were non-metropolitan?</strong><br>
Answer: Montana</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">tapply</span>(<span class="fu">is.na</span>(CPS<span class="sc">$</span>MetroAreaCode), CPS<span class="sc">$</span>State, mean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>District of Columbia           New Jersey         Rhode Island 
          0.00000000           0.00000000           0.00000000 
          California              Florida        Massachusetts 
          0.02048401           0.03923092           0.06492199 
            Maryland             New York          Connecticut 
          0.06937500           0.08060769           0.08568406 
            Illinois             Colorado              Arizona 
          0.11221881           0.12991453           0.13154450 
              Nevada                Texas            Louisiana 
          0.13308190           0.14370496           0.16137931 
        Pennsylvania             Michigan           Washington 
          0.17430025           0.17825661           0.18131868 
             Georgia             Virginia                 Utah 
          0.19843249           0.19844226           0.21009772 
              Oregon             Delaware           New Mexico 
          0.21821925           0.23396567           0.24500907 
              Hawaii                 Ohio              Alabama 
          0.24916627           0.25122349           0.25872093 
             Indiana            Wisconsin       South Carolina 
          0.29141717           0.29932986           0.31302774 
           Minnesota             Oklahoma             Missouri 
          0.31506849           0.32764281           0.32867133 
           Tennessee               Kansas       North Carolina 
          0.35594170           0.36227390           0.37304315 
                Iowa             Arkansas                Idaho 
          0.48694620           0.49049965           0.49868248 
            Kentucky        New Hampshire             Nebraska 
          0.50678979           0.56874530           0.58132376 
               Maine              Vermont          Mississippi 
          0.59832081           0.65238095           0.69430894 
        South Dakota         North Dakota        West Virginia 
          0.70250000           0.73738602           0.75585522 
             Montana               Alaska              Wyoming 
          0.83607908           1.00000000           1.00000000 </code></pre>
</div>
</div>
<p>Codes like MetroAreaCode and CountryOfBirthCode are a compact way to encode factor variables with text as their possible values, and they are therefore quite common in survey datasets. In fact, all but one of the variables in this dataset were actually stored by a numeric code in the original CPS datafile.</p>
<p>When analyzing a variable stored by a numeric code, we will often want to convert it into the values the codes represent. To do this, we will use a dictionary, which maps the the code to the actual value of the variable. We have provided dictionaries <a href="https://courses.edx.org/assets/courseware/v1/fd88455abc1b5b69112daf70f3bb0c77/asset-v1:MITx+15.071x+2T2020+type@asset+block/MetroAreaCodes.csv">MetroAreaCodes.csv</a> and <a href="https://courses.edx.org/assets/courseware/v1/763710fa6703caea1cf9c708e31e99a3/asset-v1:MITx+15.071x+2T2020+type@asset+block/CountryCodes.csv">CountryCodes.csv</a>, which respectively map MetroAreaCode and CountryOfBirthCode into their true values. <strong>Read these two dictionaries into data frames MetroAreaMap and CountryMap:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>MetroAreaMap <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/MetroAreaCodes.csv"</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>CountryMap <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/CountryCodes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>3.1.1: How many observations (codes for metropolitan areas) are there in MetroAreaMap?</strong><br>
Answer: 271</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(MetroAreaMap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 271</code></pre>
</div>
</div>
<p><strong>3.1.2: How many observations (codes for countries) are there in CountryMap?</strong><br>
Answer: 149</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(CountryMap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 149</code></pre>
</div>
</div>
<p><strong>To merge in the metropolitan areas, we want to connect the field MetroAreaCode from the CPS data frame with the field Code in MetroAreaMap. The following command merges the two data frames on these columns, overwriting the CPS data frame with the result:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>CPS <span class="ot">=</span> <span class="fu">merge</span>(CPS, MetroAreaMap, <span class="at">by.x =</span> <span class="st">"MetroAreaCode"</span>, <span class="at">by.y =</span> <span class="st">"Code"</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>3.2.1: hat is the name of the variable that was added to the data frame by the merge() operation?</strong><br>
Answer: MetroArea</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CPS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   131302 obs. of  15 variables:
 $ MetroAreaCode     : int  10420 10420 10420 10420 10420 10420 10420 10420 10420 10420 ...
 $ PeopleInHousehold : int  4 4 2 4 1 3 4 4 2 3 ...
 $ Region            : chr  "Midwest" "Midwest" "Midwest" "Midwest" ...
 $ State             : chr  "Ohio" "Ohio" "Ohio" "Ohio" ...
 $ Age               : int  2 9 73 40 63 19 30 6 60 32 ...
 $ Married           : chr  NA NA "Married" "Married" ...
 $ Sex               : chr  "Male" "Male" "Female" "Female" ...
 $ Education         : chr  NA NA "Some college, no degree" "High school" ...
 $ Race              : chr  "White" "White" "White" "White" ...
 $ Hispanic          : int  0 0 0 0 0 0 0 1 0 0 ...
 $ CountryOfBirthCode: int  57 57 57 362 57 57 203 57 57 57 ...
 $ Citizenship       : chr  "Citizen, Native" "Citizen, Native" "Citizen, Native" "Citizen, Naturalized" ...
 $ EmploymentStatus  : chr  NA NA "Retired" "Not in Labor Force" ...
 $ Industry          : chr  NA NA NA NA ...
 $ MetroArea         : chr  "Akron, OH" "Akron, OH" "Akron, OH" "Akron, OH" ...</code></pre>
</div>
</div>
<p><strong>3.2.2: How many interviewees have a missing value for the new metropolitan area variable?</strong><br>
Answer: 34238</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(CPS<span class="sc">$</span>MetroArea))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34238</code></pre>
</div>
</div>
<p><strong>3.3: Which of the following metropolitan areas has the largest number of interviewees?</strong><br>
Answer: Boston-Cambridge-Quincy, MA-NH</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(CPS<span class="sc">$</span>MetroArea), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
New York-Northern New Jersey-Long Island, NY-NJ-PA 
                                              5409 
      Washington-Arlington-Alexandria, DC-VA-MD-WV 
                                              4177 
              Los Angeles-Long Beach-Santa Ana, CA 
                                              4102 
          Philadelphia-Camden-Wilmington, PA-NJ-DE 
                                              2855 
               Chicago-Naperville-Joliet, IN-IN-WI 
                                              2772 
              Providence-Fall River-Warwick, MA-RI 
                                              2284 
                    Boston-Cambridge-Quincy, MA-NH 
                                              2229 
            Minneapolis-St Paul-Bloomington, MN-WI 
                                              1942 
                   Dallas-Fort Worth-Arlington, TX 
                                              1863 
                    Houston-Baytown-Sugar Land, TX 
                                              1649 
                                      Honolulu, HI 
                                              1576 
             Miami-Fort Lauderdale-Miami Beach, FL 
                                              1554 
                Atlanta-Sandy Springs-Marietta, GA 
                                              1552 
                                 Denver-Aurora, CO 
                                              1504 
                              Baltimore-Towson, MD 
                                              1483 
                 San Francisco-Oakland-Fremont, CA 
                                              1386 
                        Detroit-Warren-Livonia, MI 
                                              1354 
                            Las Vegas-Paradise, NV 
                                              1299 
                      Riverside-San Bernardino, CA 
                                              1290 
                       Seattle-Tacoma-Bellevue, WA 
                                              1255 
               Portland-Vancouver-Beaverton, OR-WA 
                                              1089 
                       Phoenix-Mesa-Scottsdale, AZ 
                                               971 
                                Kansas City, MO-KS 
                                               962 
                       Omaha-Council Bluffs, NE-IA 
                                               957 
                                  St. Louis, MO-IL 
                                               956 
                 San Diego-Carlsbad-San Marcos, CA 
                                               907 
          Hartford-West Hartford-East Hartford, CT 
                                               885 
               Tampa-St. Petersburg-Clearwater, FL 
                                               842 
                                    Pittsburgh, PA 
                                               732 
                   Bridgeport-Stamford-Norwalk, CT 
                                               730 
                                Salt Lake City, UT 
                                               723 
                   Cincinnati-Middletown, OH-KY-IN 
                                               719 
                 Milwaukee-Waukesha-West Allis, WI 
                                               714 
                       Portland-South Portland, ME 
                                               701 
                       Cleveland-Elyria-Mentor, OH 
                                               681 
                San Jose-Sunnyvale-Santa Clara, CA 
                                               670 
             Sacramento-Arden-Arcade-Roseville, CA 
                                               667 
                   Burlington-South Burlington, VT 
                                               657 
                              Boise City-Nampa, ID 
                                               644 
                                       Orlando, FL 
                                               610 
                                   Albuquerque, NM 
                                               609 
                                   San Antonio, TX 
                                               607 
                                 Oklahoma City, OK 
                                               604 
        Virginia Beach-Norfolk-Newport News, VA-NC 
                                               597 
                                   Sioux Falls, SD 
                                               595 
                                  Indianapolis, IN 
                                               570 
                                      Columbus, OH 
                                               551 
                                 Louisville, KY-IN 
                                               519 
                 Charlotte-Gastonia-Concord, NC-SC 
                                               517 
                             Austin-Round Rock, TX 
                                               516 
                                     New Haven, CT 
                                               506 
               Nashville-Davidson-Murfreesboro, TN 
                                               505 
                                    Des Moines, IA 
                                               501 
                                      Richmond, VA 
                                               490 
                                         Dover, DE 
                                               456 
                                      Fargo, ND-MN 
                                               432 
                                       Wichita, KS 
                                               427 
                              Ogden-Clearfield, UT 
                                               423 
                 Little Rock-North Little Rock, AR 
                                               404 
                                  Jacksonville, FL 
                                               393 
                             Birmingham-Hoover, AL 
                                               392 
                              Colorado Springs, CO 
                                               372 
                   New Orleans-Metairie-Kenner, LA 
                                               367 
                                 Memphis, TN-MS-AR 
                                               348 
                         Buffalo-Niagara Falls, NY 
                                               344 
                                  Raleigh-Cary, NC 
                                               336 
                 Allentown-Bethlehem-Easton, PA-NJ 
                                               334 
                                         Tulsa, OK 
                                               323 
                                   Reno-Sparks, NV 
                                               310 
                                    Provo-Orem, UT 
                                               309 
                                     Rochester, NY 
                                               307 
                          Grand Rapids-Wyoming, MI 
                                               304 
                                        Fresno, CA 
                                               303 
                                        Tucson, AZ 
                                               302 
                                      Columbia, SC 
                                               291 
                                       Madison, WI 
                                               284 
                       Albany-Schenectady-Troy, NY 
                                               268 
                                        Dayton, OH 
                                               268 
                  Oxnard-Thousand Oaks-Ventura, CA 
                                               267 
                                   Baton Rouge, LA 
                                               262 
                                    Charleston, WV 
                                               262 
                            Rochester-Dover, NH-ME 
                                               262 
                         Greensboro-High Point, NC 
                                               251 
                                   Bakersfield, CA 
                                               245 
                                       El Paso, TX 
                                               244 
               Davenport-Moline-Rock Island, IA-IL 
                                               240 
                                        Toledo, OH 
                                               235 
                   Charleston-North Charleston, SC 
                                               232 
                                         Akron, OH 
                                               231 
                                      Syracuse, NY 
                                               223 
                                       Jackson, MS 
                                               222 
             Fayetteville-Springdale-Rogers, AR-MO 
                                               215 
                                        Bangor, ME 
                                               208 
                         Fort Collins-Loveland, CO 
                                               206 
                         Norwich-New London, CT-RI 
                                               203 
                                      Savannah, GA 
                                               202 
              Poughkeepsie-Newburgh-Middletown, NY 
                                               201 
                                      Billings, MT 
                                               199 
                             Lexington-Fayette, KY 
                                               198 
                                  Cedar Rapids, IA 
                                               196 
                            Eugene-Springfield, OR 
                                               196 
                        McAllen-Edinburg-Pharr, TX 
                                               195 
                                      Stockton, CA 
                                               193 
                     Sarasota-Bradenton-Venice, FL 
                                               192 
                                        Durham, NC 
                                               189 
                                    Greenville, SC 
                                               185 
                                        Topeka, KS 
                                               182 
                                     Lafayette, LA 
                                               181 
                                        Monroe, LA 
                                               179 
                         Scranton-Wilkes Barre, PA 
                                               176 
                           Harrisburg-Carlisle, PA 
                                               174 
                                       Boulder, CO 
                                               171 
                                         Salem, OR 
                                               170 
                                     Knoxville, TN 
                                               168 
                 Palm Bay-Melbourne-Titusville, FL 
                                               168 
                                Chattanooga, TN-GA 
                                               167 
                                       Greeley, CO 
                                               162 
                    Augusta-Richmond County, GA-SC 
                                               161 
                                   Springfield, MO 
                                               161 
                                       Modesto, CA 
                                               158 
                                     Waterbury, CT 
                                               157 
                                     Lancaster, PA 
                                               156 
                                       Spokane, WA 
                                               156 
                          Waterloo-Cedar Falls, IA 
                                               156 
                                Springfield, MA-CT 
                                               155 
                    Youngstown-Warren-Boardman, OH 
                                               153 
                         Lakeland-Winter Haven, FL 
                                               149 
                         Cape Coral-Fort Myers, FL 
                                               146 
                       Shreveport-Bossier City, LA 
                                               146 
                                  Worcester, MA-CT 
                                               144 
                                       Reading, PA 
                                               142 
                                          Bend, OR 
                                               140 
            Deltona-Daytona Beach-Ormond Beach, FL 
                                               140 
                                    Fort Wayne, IN 
                                               136 
                                     Green Bay, WI 
                                               136 
                             Vallejo-Fairfield, CA 
                                               133 
                                Corpus Christi, TX 
                                               132 
              Santa Barbara-Santa Maria-Goleta, CA 
                                               132 
                                     Iowa City, IA 
                                               131 
                                        Pueblo, CO 
                                               130 
                           Santa Rosa-Petaluma, CA 
                                               129 
                             Kalamazoo-Portage, MI 
                                               127 
                                 Winston-Salem, NC 
                                               127 
                                     Duluth, MN-WI 
                                               126 
                                       Appleton,WI 
                                               125 
                          Beaumont-Port Author, TX 
                                               123 
                              Champaign-Urbana, IL 
                                               122 
                           Visalia-Porterville, CA 
                                               121 
                          Lansing-East Lansing, MI 
                                               119 
                                        Racine, WI 
                                               119 
                              Canton-Massillon, OH 
                                               118 
                                 Coeur d'Alene, ID 
                                               117 
                                    Huntsville, AL 
                                               117 
                                  York-Hanover, PA 
                                               117 
                                     Asheville, NC 
                                               116 
                                      Victoria, TX 
                                               116 
                                     La Crosse, WI 
                                               114 
                                      Rockford, IL 
                                               114 
                                       Danbury, CT 
                                               112 
                                        Peoria, IL 
                                               112 
                                        Yakima, WA 
                                               112 
                                 Atlantic City, NJ 
                                               111 
                                    Eau Claire, WI 
                                               110 
                                        Mobile, AL 
                                               110 
                    Port St. Lucie-Fort Pierce, FL 
                                               109 
                                    Las Cruses, NM 
                                               107 
                    Pensacola-Ferry Pass-Brent, FL 
                                               107 
                                        Merced, CA 
                                               106 
                                 Fort Smith, AR-OK 
                                               105 
                                   Bloomington, IN 
                                               104 
                                       Salinas, CA 
                                               104 
                                    Montgomery, AL 
                                               103 
                                         Flint, MI 
                                               102 
        Myrtle Beach-Conway-North Myrtle Beach, SC 
                                               102 
                      Killeen-Temple-Fort Hood, TX 
                                               101 
                                     El Centro, CA 
                                                99 
                                 Evansville, IN-KY 
                                                99 
                                    Janesville, WI 
                                                99 
                                       Olympia, WA 
                                                99 
                                   Spartanburg, SC 
                                                99 
                                      Lawrence, KS 
                                                98 
                                        Lawton, OK 
                                                97 
                                       Decatur, Al 
                                                96 
                                        Wausau, WI 
                                                96 
                                 Trenton-Ewing, NJ 
                                                91 
                                  Harrisonburg, VA 
                                                90 
                        Muskegon-Norton Shores, MI 
                                                90 
                                        Laredo, TX 
                                                89 
                                      Amarillo, TX 
                                                88 
                          Bremerton-Silverdale, WA 
                                                87 
                                          Erie, PA 
                                                87 
                              Kankakee-Bradley, IL 
                                                87 
                                      Kingston, NY 
                                                87 
                     Hagerstown-Martinsburg, MD-WV 
                                                86 
                                     Ann Arbor, MI 
                                                85 
                                Oshkosh-Neenah, WI 
                                                85 
                                       Altoona, PA 
                                                82 
                      Huntington-Ashland, WV-KY-OH 
                                                82 
                                       Medford, OR 
                                                82 
                           Naples-Marco Island, FL 
                                                82 
                                     St. Cloud, MN 
                                                82 
                                       Decatur, IL 
                                                81 
                                  Lake Charles, LA 
                                                81 
                       South Bend-Mishawaka, IN-MI 
                                                81 
            Fort Walton Beach-Crestview-Destin, FL 
                                                80 
                                    Utica-Rome, NY 
                                                80 
                         Brownsville-Harlingen, TX 
                                                79 
                                    Vero Beach, FL 
                                                79 
                                          Waco, TX 
                                                79 
                           Holland-Grand Haven, MI 
                                                78 
                                    Tuscaloosa, AL 
                                                78 
                                  Fayetteville, NC 
                                                77 
                        Michigan City-La Porte, IN 
                                                77 
                   San Luis Obispo-Paso Robles, CA 
                                                77 
                                         Ocala, FL 
                                                76 
                                   Springfield, IL 
                                                76 
                               Barnstable Town, MA 
                                                75 
                Saginaw-Saginaw Township North, MI 
                                                74 
                                     Salisbury, MD 
                                                74 
                                    Binghamton, NY 
                                                73 
                                     Lynchburg, VA 
                                                73 
                                    Bellingham, WA 
                                                70 
                                   Gainesville, FL 
                                                70 
                                       Jackson, MI 
                                                70 
                                        Albany, GA 
                                                68 
                          Kingsport-Bristol, TN-VA 
                                                67 
                  Leominster-Fitchburg-Gardner, MA 
                                                66 
                                       Roanoke, VA 
                                                66 
                        Santa-Cruz-Watsonville, CA 
                                                66 
                           Athens-Clark County, GA 
                                                65 
                               Gulfport-Biloxi, MS 
                                                65 
                                      Longview, TX 
                                                65 
                                         Macon, GA 
                                                65 
                                      Anderson, SC 
                                                64 
                                    Farmington, NM 
                                                64 
                                      Florence, AL 
                                                63 
                                  Jacksonville, NC 
                                                63 
                                     Johnstown, PA 
                                                63 
                                       Lubbock, TX 
                                                63 
                                        Monroe, MI 
                                                63 
                                      Anderson, IN 
                                                62 
                               Anniston-Oxford, AL 
                                                61 
                                          Napa, CA 
                                                61 
                                         Chico, CA 
                                                60 
                                   Columbus, GA-AL 
                                                59 
                                        Joplin, MO 
                                                59 
                        Panama City-Lynn Haven, FL 
                                                59 
                     Hickory-Morgantown-Lenoir, NC 
                                                57 
                                        Madera, CA 
                                                57 
                                      Prescott, AZ 
                                                54 
                  Vineland-Millville-Bridgeton, NJ 
                                                54 
                                  Johnson City, TN 
                                                52 
                                      Santa Fe, NM 
                                                52 
                                       Midland, TX 
                                                51 
                           Niles-Benton Harbor, MI 
                                                51 
                                   Punta Gorda, FL 
                                                48 
                                      Columbia, MO 
                                                47 
                                   Tallahassee, FL 
                                                43 
                                      Valdosta, GA 
                                                42 
                                 Warner Robins, GA 
                                                42 
                             Bloomington-Normal IL 
                                                40 
                                   Springfield, OH 
                                                34 
                                    Ocean City, NJ 
                                                30 
                                 Bowling Green, KY 
                                                29 </code></pre>
</div>
</div>
<p><strong>3.4: Which metropolitan area has the highest proportion of interviewees of Hispanic ethnicity?</strong><br>
Answer: Laredo, TX</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Hispanic, CPS<span class="sc">$</span>MetroArea, mean), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Laredo, TX 
 0.9662921 </code></pre>
</div>
</div>
<p><strong>3.5: Determine the number of metropolitan areas in the United States from which at least 20% of interviewees are Asian.</strong><br>
Answer: 4</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Race <span class="sc">==</span> <span class="st">"Asian"</span>, CPS<span class="sc">$</span>MetroArea, mean), <span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p><strong>3.6: Determine which metropolitan area has the smallest proportion of interviewees who have received no high school diploma.</strong><br>
Answer: Iowa City, IA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Education <span class="sc">==</span> <span class="st">"No high school diploma"</span>, CPS<span class="sc">$</span>MetroArea, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Iowa City, IA 
   0.02912621 </code></pre>
</div>
</div>
<p><strong>Just as we did with the metropolitan area information, merge in the country of birth information from the CountryMap data frame, replacing the CPS data frame with the result:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>CPS <span class="ot">=</span> <span class="fu">merge</span>(CPS, CountryMap, <span class="at">by.x =</span> <span class="st">"CountryOfBirthCode"</span>, <span class="at">by.y =</span> <span class="st">"Code"</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>4.1.1: What is the name of the variable added to the CPS data frame by this merge operation?</strong><br>
Answer: Country</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CPS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   131302 obs. of  16 variables:
 $ CountryOfBirthCode: int  57 57 57 57 57 57 57 57 57 57 ...
 $ MetroAreaCode     : int  10420 71650 10420 10420 10420 10420 10420 10420 10420 10420 ...
 $ PeopleInHousehold : int  2 4 5 2 2 3 1 3 4 4 ...
 $ Region            : chr  "Midwest" "Northeast" "Midwest" "Midwest" ...
 $ State             : chr  "Ohio" "New Hampshire" "Ohio" "Ohio" ...
 $ Age               : int  73 5 10 30 30 0 34 32 6 9 ...
 $ Married           : chr  "Married" NA NA "Married" ...
 $ Sex               : chr  "Female" "Female" "Female" "Female" ...
 $ Education         : chr  "Some college, no degree" NA NA "Associate degree" ...
 $ Race              : chr  "White" "White" "White" "White" ...
 $ Hispanic          : int  0 0 0 0 0 0 0 0 1 0 ...
 $ Citizenship       : chr  "Citizen, Native" "Citizen, Native" "Citizen, Native" "Citizen, Native" ...
 $ EmploymentStatus  : chr  "Retired" NA NA "Employed" ...
 $ Industry          : chr  NA NA NA "Trade" ...
 $ MetroArea         : chr  "Akron, OH" "Boston-Cambridge-Quincy, MA-NH" "Akron, OH" "Akron, OH" ...
 $ Country           : chr  "United States" "United States" "United States" "United States" ...</code></pre>
</div>
</div>
<p><strong>4.1.2: How many interviewees have a missing value for the new country of birth variable?</strong><br>
Answer: 176</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(CPS<span class="sc">$</span>Country))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 176</code></pre>
</div>
</div>
<p><strong>4.2: Among all interviewees born outside of North America, which country was the most common place of birth?</strong><br>
Answer: Philippines</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(CPS<span class="sc">$</span>Country), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
United States        Mexico   Philippines 
       115063          3921           839 </code></pre>
</div>
</div>
<p><strong>4.3: What proportion of the interviewees from the “New York-Northern New Jersey-Long Island, NY-NJ-PA” metropolitan area have a country of birth that is not the United States? For this computation, don’t include people from this metropolitan area who have a missing country of birth.</strong><br>
Answer: 0.3086603</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(CPS<span class="sc">$</span>Country <span class="sc">!=</span> <span class="st">"United States"</span>, CPS<span class="sc">$</span>MetroArea <span class="sc">==</span> <span class="st">"New York-Northern New Jersey-Long Island, NY-NJ-PA"</span>, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    FALSE      TRUE 
0.1392772 0.3086603 </code></pre>
</div>
</div>
<p><strong>4.4: Which metropolitan area has the largest number (note – not proportion) of interviewees with a country of birth…</strong> <strong>4.4.1: …in India?</strong><br>
Answer: New York-Northern New Jersey-Long Island, NY-NJ-PA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"India"</span>, CPS<span class="sc">$</span>MetroArea, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>New York-Northern New Jersey-Long Island, NY-NJ-PA 
                                                96 </code></pre>
</div>
</div>
<p><strong>4.4.2: …in Brazil?</strong><br>
Answer: Boston-Cambridge-Quincy, MA-NH</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"Brazil"</span>, CPS<span class="sc">$</span>MetroArea, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Boston-Cambridge-Quincy, MA-NH 
                            18 </code></pre>
</div>
</div>
<p><strong>4.4.3: …in Somalia?</strong><br>
Answer: Minneapolis-St Paul-Bloomington, MN-WI</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">sort</span>(<span class="fu">tapply</span>(CPS<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"Somalia"</span>, CPS<span class="sc">$</span>MetroArea, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Minneapolis-St Paul-Bloomington, MN-WI 
                                    17 </code></pre>
</div>
</div>
</section>
<section id="internet-privacy-poll-optional" class="level2">
<h2 class="anchored" data-anchor-id="internet-privacy-poll-optional">Internet Privacy Poll (OPTIONAL)</h2>
<p>Internet privacy has gained widespread attention in recent years. To measure the degree to which people are concerned about hot-button issues like Internet privacy, social scientists conduct polls in which they interview a large number of people about the topic. In this assignment, we will analyze data from a July 2013 Pew Internet and American Life Project poll on Internet anonymity and privacy, which involved interviews across the United States. While the full polling data can be found here, we will use a more limited version of the results, available in <a href="https://courses.edx.org/assets/courseware/v1/f2c3bdcba475ddd1399e001dd98f4fd0/asset-v1:MITx+15.071x+2T2020+type@asset+block/AnonymityPoll.csv">AnonymityPoll.csv</a>.</p>
<p><strong><em>Start:</em></strong><br>
Using read.csv(), load the dataset from AnonymityPoll.csv into a data frame called poll.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>poll <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/cloud/project/analyticsedge/Datasets/DatasetsUnit1/AnonymityPoll.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>1.1: How many people participated in the poll?</strong><br>
Answer: 1002</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(poll)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1002</code></pre>
</div>
</div>
<p><strong>1.2.1: How many interviewees responded that they use a smartphone?</strong><br>
Answer: 487</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(poll<span class="sc">$</span>Smartphone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 487</code></pre>
</div>
</div>
<p><strong>1.2.2: How many interviewees responded that they don’t use a smartphone?</strong><br>
Answer: 472</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(poll<span class="sc">$</span>Smartphone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
472 487 </code></pre>
</div>
</div>
<p><strong>1.2.3: How many interviewees did not respond to the question, resulting in a missing value, or NA, in the summary() output?</strong><br>
Answer: 43</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(poll<span class="sc">$</span>Smartphone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43</code></pre>
</div>
</div>
<p><strong>1.3.1: Which of the following are states in the Midwest census region?</strong><br>
Answer: Kansas, Missouri, Ohio</p>
<p><strong>1.3.2: Which was the state in the South census region with the largest number of interviewees?</strong><br>
Answer: Texas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(poll<span class="sc">$</span>Region, poll<span class="sc">$</span>State)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            Alabama Arizona Arkansas California Colorado Connecticut Delaware
  Midwest         0       0        0          0        0           0        0
  Northeast       0       0        0          0        0           8        0
  South          11       0       10          0        0           0        6
  West            0      24        0        103       19           0        0
           
            District of Columbia Florida Georgia Idaho Illinois Indiana Iowa
  Midwest                      0       0       0     0       32      27   14
  Northeast                    0       0       0     0        0       0    0
  South                        2      42      34     0        0       0    0
  West                         0       0       0     8        0       0    0
           
            Kansas Kentucky Louisiana Maine Maryland Massachusetts Michigan
  Midwest       14        0         0     0        0             0       31
  Northeast      0        0         0     4        0            19        0
  South          0       25        17     0       18             0        0
  West           0        0         0     0        0             0        0
           
            Minnesota Mississippi Missouri Montana Nebraska Nevada
  Midwest          15           0       26       0       11      0
  Northeast         0           0        0       0        0      0
  South             0          11        0       0        0      0
  West              0           0        0       5        0      8
           
            New Hampshire New Jersey New Mexico New York North Carolina
  Midwest               0          0          0        0              0
  Northeast             7         16          0       60              0
  South                 0          0          0        0             32
  West                  0          0          5        0              0
           
            North Dakota Ohio Oklahoma Oregon Pennsylvania Rhode Island
  Midwest              5   38        0      0            0            0
  Northeast            0    0        0      0           45            4
  South                0    0       14      0            0            0
  West                 0    0        0     20            0            0
           
            South Carolina South Dakota Tennessee Texas Utah Vermont Virginia
  Midwest                0            3         0     0    0       0        0
  Northeast              0            0         0     0    0       3        0
  South                 12            0        17    72    0       0       31
  West                   0            0         0     0   11       0        0
           
            Washington West Virginia Wisconsin Wyoming
  Midwest            0             0        23       0
  Northeast          0             0         0       0
  South              0             5         0       0
  West              28             0         0       7</code></pre>
</div>
</div>
<p><strong>2.1.1: How many interviewees reported not having used the Internet and not having used a smartphone?</strong><br>
Answer: 186</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(poll<span class="sc">$</span>Internet.Use <span class="sc">==</span> <span class="dv">0</span>, poll<span class="sc">$</span>Smartphone <span class="sc">==</span> <span class="dv">0</span>, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE  TRUE 
   17   186 </code></pre>
</div>
</div>
<p><strong>2.1.2: How many interviewees reported having used the Internet and having used a smartphone?</strong><br>
Answer: 470</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(poll<span class="sc">$</span>Internet.Use, poll<span class="sc">$</span>Smartphone, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0   1 
285 470 </code></pre>
</div>
</div>
<p><strong>2.1.3: How many interviewees reported having used the Internet but not having used a smartphone?</strong><br>
Answer: 285</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(poll<span class="sc">$</span>Internet.Use <span class="sc">==</span> <span class="dv">1</span>, poll<span class="sc">$</span>Smartphone <span class="sc">==</span> <span class="dv">0</span>, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE  TRUE 
  470   285 </code></pre>
</div>
</div>
<p><strong>2.1.4: How many interviewees reported having used a smartphone but not having used the Internet?</strong><br>
Answer: 17</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(poll<span class="sc">$</span>Internet.Use <span class="sc">==</span> <span class="dv">0</span>, poll<span class="sc">$</span>Smartphone <span class="sc">==</span> <span class="dv">1</span>, sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE  TRUE 
  186    17 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative to all 4 above questions: table(poll$Internet.Use, poll$Smartphone)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>2.2.1: How many interviewees have a missing value for their Internet use?</strong><br>
Answer: 1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(poll<span class="sc">$</span>Internet.Use))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p><strong>2.2.2: How many interviewees have a missing value for their smartphone use?</strong><br>
Answer: 43</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(poll<span class="sc">$</span>Smartphone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43</code></pre>
</div>
</div>
<p><strong>Use the subset function to obtain a data frame called “limited”, which is limited to interviewees who reported Internet use or who reported smartphone use:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>limited <span class="ot">&lt;-</span> <span class="fu">subset</span>(poll, poll<span class="sc">$</span>Internet.Use <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">|</span>poll<span class="sc">$</span>Smartphone <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative: limited = subset(poll, Internet.Use == 1 | Smartphone == 1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>2.3: How many interviewees are in the new data frame?</strong><br>
Answer: 792</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(limited)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 792</code></pre>
</div>
</div>
<p><strong>3.1: Which variables have missing values in the limited data frame?</strong><br>
Answer: <em>Check output</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(limited)) <span class="sc">&gt;</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Smartphone"             "Age"                    "Conservativeness"      
[4] "Worry.About.Info"       "Privacy.Importance"     "Anonymity.Possible"    
[7] "Tried.Masking.Identity" "Privacy.Laws.Effective"</code></pre>
</div>
</div>
<p><strong>3.2: What is the average number of pieces of personal information on the Internet, according to the Info.On.Internet variable?</strong><br>
Answer: 3.795455</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(limited<span class="sc">$</span>Info.On.Internet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.795455</code></pre>
</div>
</div>
<p><strong>3.3.1: How many interviewees reported a value of 0 for Info.On.Internet?</strong><br>
Answer: 105</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(limited<span class="sc">$</span>Info.On.Internet <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105</code></pre>
</div>
</div>
<p><strong>3.3.2: How many interviewees reported the maximum value of 11 for Info.On.Internet?</strong><br>
Answer: 8</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb170"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb170-1"><a href="#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(limited<span class="sc">$</span>Info.On.Internet <span class="sc">==</span> <span class="dv">11</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p><strong>3.4: What proportion of interviewees who answered the Worry.About.Info question worry about how much information is available about them on the Internet?</strong><br>
Answer: 0.4886076</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb172"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(limited<span class="sc">$</span>Worry.About.Info)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
404 386 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb174"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb174-1"><a href="#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="dv">386</span><span class="sc">/</span>(<span class="dv">404</span> <span class="sc">+</span> <span class="dv">386</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4886076</code></pre>
</div>
</div>
<p><strong>3.5: What proportion of interviewees who answered the Anonymity.Possible question think it is possible to be completely anonymous on the Internet?</strong><br>
Answer: 0.3691899</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb176"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(limited<span class="sc">$</span>Anonymity.Possible)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
475 278 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb178"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb178-1"><a href="#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="dv">278</span><span class="sc">/</span>(<span class="dv">475</span> <span class="sc">+</span> <span class="dv">278</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3691899</code></pre>
</div>
</div>
<p><strong>3.6: What proportion of interviewees who answered the Tried.Masking.Identity question have tried masking their identity on the Internet?</strong><br>
Answer: 0.1632653</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb180"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb180-1"><a href="#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(limited<span class="sc">$</span>Tried.Masking.Identity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
656 128 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb182"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb182-1"><a href="#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="dv">128</span><span class="sc">/</span>(<span class="dv">656</span> <span class="sc">+</span> <span class="dv">128</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1632653</code></pre>
</div>
</div>
<p><strong>3.7: What proportion of interviewees who answered the Privacy.Laws.Effective question find United States privacy laws effective?</strong><br>
Answer: 0.2558459</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb184"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb184-1"><a href="#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(limited<span class="sc">$</span>Privacy.Laws.Effective)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
541 186 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb186"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb186-1"><a href="#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="dv">186</span><span class="sc">/</span>(<span class="dv">541</span> <span class="sc">+</span> <span class="dv">186</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2558459</code></pre>
</div>
</div>
<p><strong>4.1: Build a histogram of the age of interviewees. What is the best represented age group in the population?</strong><br>
Answer: People aged about 60 years old.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb188"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb188-1"><a href="#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(limited<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-95-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Both Age and Info.On.Internet are variables that take on many values, so a good way to observe their relationship is through a graph. We learned in lecture that we can plot Age against Info.On.Internet with the command <code>plot(limited$Age, limited$Info.On.Internet)</code>. However, because Info.On.Internet takes on a small number of values, multiple points will be plotted in exactly the same location on this graph, making the distribution hard to see:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb189"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb189-1"><a href="#cb189-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(limited<span class="sc">$</span>Age, limited<span class="sc">$</span>Info.On.Internet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-96-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>4.2: What is the largest number of interviewees that have exactly the same value in their Age variable AND the same value in their Info.On.Internet variable?</strong><br>
Answer: 6</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb190"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb190-1"><a href="#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">table</span>(limited<span class="sc">$</span>Age, limited<span class="sc">$</span>Info.On.Internet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p><strong>4.3: Experimenting with the command jitter(c(1, 2, 3)), what appears to be the functionality of the jitter command?</strong><br>
Answer: jitter adds or subtracts a small amount of random noise to the values passed to it, and two runs will yield different results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb192"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb192-1"><a href="#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">jitter</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.040771 1.970155 3.152792</code></pre>
</div>
</div>
<p><strong>4.4: What relationship to you observe between Age and Info.On.Internet?</strong><br>
Answer: Older age seems moderately associated with a smaller value for Info.On.Internet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb194"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb194-1"><a href="#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">jitter</span>(limited<span class="sc">$</span>Age), <span class="fu">jitter</span>(limited<span class="sc">$</span>Info.On.Internet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment1_files/figure-html/unnamed-chunk-99-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>4.5.1: What is the average Info.On.Internet value for smartphone users?</strong><br>
Answer: 4.367556</p>
<p><strong>4.5.2: What is the average Info.On.Internet value for non-smartphone users?</strong><br>
Answer: 2.922807</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb195"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb195-1"><a href="#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(limited<span class="sc">$</span>Info.On.Internet, limited<span class="sc">$</span>Smartphone, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
2.922807 4.367556 </code></pre>
</div>
</div>
<p><strong>4.6.1: What proportion of smartphone users who answered the Tried.Masking.Identity question have tried masking their identity when using the Internet?</strong><br>
Answer: 0.1925466</p>
<p><strong>4.6.2: What proportion of non-smartphone users who answered the Tried.Masking.Identity question have tried masking their identity when using the Internet?</strong><br>
Answer: 0.1174377</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb197"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb197-1"><a href="#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(limited<span class="sc">$</span>Tried.Masking.Identity, limited<span class="sc">$</span>Smartphone, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0         1 
0.1174377 0.1925466 </code></pre>
</div>
</div>
<p><strong><em>And we’re done! That was all for Assignment 1!</em></strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">The Analytics Edge: Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Assignments/Assignment2.html" class="pagination-link">
        <span class="nav-page-text">The Analytics Edge: Assignment 2 - Linear Regression</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>